services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-pw
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network

  mailpit:
    image: axllent/mailpit
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025

  # app:
  #   build:
  #     context: .
  #   environment:
  #     DB_USER: db-user
  #     DB_PASSWORD: db-pw
  #     DB_DB: db
  #     DB_PORT: 5432
  #     DB_HOST: db
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - network

volumes:
  db_data:

networks:
  network:
